# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OCTemplateDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for OCTemplateDemo
  inhibit_all_warnings!
  
  pod 'BGFMDB', '~> 2.0.9'
  pod 'MBProgressHUD'
  pod 'AFNetworking'
  pod 'Masonry'
  pod 'MMDrawerController'
  pod 'MJExtension'
  pod 'IQKeyboardManager','~> 5.0.6'
  pod 'BRPickerView'
  pod 'SDWebImage','~>4.4.2'
  pod 'ReactiveCocoa', :git => 'https://github.com/zhao0/ReactiveCocoa.git', :tag => '2.5.2'
  pod 'YYCache'
  pod 'YYText'

end
