# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OCTemplateDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for OCTemplateDemo
  pod 'BGFMDB', '~> 2.0.9'
  pod 'MBProgressHUD'
  pod 'AFNetworking'
  pod 'Masonry'

end
